# image will be published to ghcr.io/<user>/<name>
name: atomic-saigon
# description will be included in the image's metadata
description: the saigoneer's ublue-kinoite spin

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - fastfetch
      - kde-print-manager
      - krusader
      - eza
      - mc
      - micro
      - zsh
      - zsh-autosuggestions
      - zsh-html
      - zsh-syntax-highlighting
      
    remove:
      - firefox
      - firefox-langpacks
      - google-noto-serif-fonts
      - google-noto-sans-cjk-fonts
      - kcharselect
      - kde-connect
      - kde-connect-libs
      - kdeconnectd
      - kfind
      - krfb
      - krfb-libs
      - nvtop
      - plasma-discover-notifier
      - plasma-welcome

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.brave.Browser
        # - org.gnome.Loupe
        # - one.ablaze.floorp
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
