# image will be published to ghcr.io/<user>/<name>
name: atomic-saigon
# description will be included in the image's metadata
description: the saigoneer's cosmic bluebuild spin

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic
image-version: 40 # latest is also supported if you want new updates ASAP
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - fastfetch
      
    remove:
      - firefox
      - firefox-langpacks
      - nvtop
      - default-fonts-as
      - default-fonts-bn
      - default-fonts-mni
      - default-fonts-other-sans
      - default-fonts-hi
      - default-fonts-mai
      - default-fonts-mr
      - default-fonts-ast
      - default-fonts-be
      - default-fonts-bg
      - default-fonts-br
      - default-fonts-dz
      - default-fonts-el
      - default-fonts-eo
      - default-fonts-eu
      - default-fonts-ia
      - default-fonts-ku
      - default-fonts-nb
      - default-fonts-nn
      - default-fonts-nr
      - default-fonts-nso
      - default-fonts-ru
      - default-fonts-ss
      - default-fonts-tn
      - default-fonts-ts
      - default-fonts-uk
      - default-fonts-ve
      - default-fonts-vi
      - default-fonts-xh
      - default-fonts-yi
      - default-fonts-zu
      - google-noto-sans-ethiopic-vf-fonts
      - default-fonts-am
      - google-noto-sans-arabic-vf-fonts
      - default-fonts-ar
      - google-noto-sans-cherokee-vf-fonts
      - default-fonts-chr
      - google-noto-sans-thaana-vf-fonts
      - default-fonts-dv
      - google-noto-sans-gujarati-vf-fonts
      - default-fonts-gu
      - google-noto-sans-hebrew-vf-fonts
      - default-fonts-he
      - google-noto-sans-armenian-vf-fonts
      - default-fonts-hy
      - google-noto-sans-canadian-aboriginal-vf-fonts
      - default-fonts-iu
      - google-noto-sans-georgian-vf-fonts
      - default-fonts-ka
      - google-noto-sans-khmer-vf-fonts
      - default-fonts-km
      - google-noto-sans-kannada-vf-fonts
      - default-fonts-kn
      - google-noto-sans-lao-vf-fonts
      - default-fonts-lo
      - google-noto-sans-meeteimayek-vf-fonts
      - google-noto-sans-oriya-vf-fonts
      - default-fonts-or
      - google-noto-sans-gurmukhi-vf-fonts
      - default-fonts-pa
      - google-noto-sans-ol-chiki-vf-fonts
      - default-fonts-sat
      - google-noto-sans-sinhala-vf-fonts
      - default-fonts-si
      - google-noto-sans-tamil-vf-fonts
      - default-fonts-ta
      - google-noto-sans-telugu-vf-fonts
      - default-fonts-te
      - google-noto-sans-thai-vf-fonts
      - default-fonts-th
      - jomolhari-fonts
      - default-fonts-bo
      - vazirmatn-vf-fonts
      - default-fonts-fa
      - sil-padauk-fonts
      - default-fonts-my
      - madan-fonts
      - default-fonts-ne
      - sil-nuosu-fonts
      - paktype-naskh-basic-fonts
      - default-fonts-ur
      - rit-meera-new-fonts
      - default-fonts-ml
      - google-noto-naskh-arabic-fonts
      - google-noto-sans-devanagari-vf-fonts
      - google-noto-sans-bengali-vf-fonts
      - google-noto-sans-balinese-fonts
      - google-noto-sans-cjk-fonts
      - google-droid-sans-fonts
      - google-noto-sans-kr-fonts
      - google-noto-sans-tc-fonts
      - google-noto-sans-sc-fonts
      - google-noto-sans-javanese-fonts
      - google-noto-sans-sundanese-fonts
      - sil-mingzat-fonts

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - io.github.zen_browser.zen
        # - org.gnome.Loupe
        # - one.ablaze.floorp
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
